# Generated by Django 4.2.16 on 2024-10-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=18, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=18, verbose_name='手机号')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('info', models.CharField(max_length=200, verbose_name='详细地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.userinfo', verbose_name='所属用户')),
            ],
        ),
    ]
